### ISSUE TITLE
Problem with PortException

### ISSUE THREAD

**Issue by stevan-borus** [PyramidTechnologies/netPyramid-RS-232#11]
I've set the RS232 Validator in escrow mode and every time I put the bill in it fires the OnError event with Timeout whether it goes in or it doesn't (sometimes it doesn't go in and the bill acts like it's in).
And it throws the PTI.Serial.PortException. I can't catch this because it happens in the DLL and I don't know why is that happening.
Can you explain maybe what is going on?
And the other issue I have is that when it comes in escrow event and when the bill is about to be Stacked or Rejected, the acceptor just returns the bill out and it constantly fires OnStateChanged event with Returned as a state. Even when I reconnect the acceptor it still does this until I put the bill back in again.

**Comment by codygillespie** [comment]
@steeeve12 could you please post the name of the firmware that the bill acceptor is using?

**Comment by stevan-borus** [comment]
@codygillespie The Acceptor Tools 7.5.0 won't find my acceptor so I can't check the firmware. Can I check it somewhere else?
When I start the RS232 Test App the acceptor connects successfully.

**Comment by codygillespie** [comment]
> The Acceptor Tools 7.5.0 won't find my acceptor

@steeeve12 are you by chance using the 18-pin RS232 cable when you attempt to connect the bill acceptor to Acceptor Tools? We will want to use the 6-pin FTDI flash memory port in order for acceptor tools to be able to find the bill acceptor.

Can you confirm for me if using the 6-pin cable allows you to connect in Acceptor Tools to view the current firmware?

**Comment by stevan-borus** [comment]
@codygillespie I'm using the 18-pin cable. 3 or 4 months ago Acceptor Tools found my acceptor over that cable and I installed the latest firmware then. Were there any changes until now?
The other problem is that I don't have the 6-pin cable. Clients didn't send me that cable.

**Comment by codygillespie** [comment]
@steeeve12 Acceptor Tools will not be able to connect to the bill acceptor without that 6 pin. I'm going to go ahead and refer this question to our Senior Engineer who will be back in office on Monday, August 24.

In the meantime, could you please post your Acceptor Tools log file? You can navigate to the log file in v7.5 by going to Help>Send Log File.

**Comment by corytodd** [comment]
You will need the 6-pin harness to update firmware and check configuration. The 18-pin port is strictly a host interface.

If you power on the Apex without starting the RS232 test app do the bezel leds light up and do bills accept?
