### ISSUE TITLE
That Cash Acceptor always blinks once after user has saticified payment

### ISSUE THREAD

**Issue by ErnestMushinge** [PyramidTechnologies/netPyramid-RS-232#9]
- [ ] When user inserts a bill and it is the last bill for the transaction. The Cash Acceptor always blinks once signaling it needs more money. Looked into the code and did not found anywhere to send a quick signal to the Validator to pause, always blinks once before it is paused.

**Comment by corytodd** [comment]
This sounds related to #8 so I'm closing this one.
